global_attrs:
    title: ${main.campaign} level 1 sounding data
    description: ???
    campaign_id: ${main.campaign_id}
    platform: ${main.platform}
    instrument: "Radiosonde RS41-SGP by Vaisala"
    instrument_id: "Vaisala-RS"
    number_of_probe: ${meta_level0.number_of_probe}
    sonde_type: ${meta_level0.sonde_type}
    sonde_frequency: ${meta_level0.sonde_frequency}
    source: ${meta_level0.source}
    doi: "10.205326/137"
    version: ???
    featureType: "trajectory"
    Conventions: "CF-1.7"

coordinates:
    sounding:
        attrs:
            cf_role : "trajecotry_id"
            long_name: "sounding identifier"
            description: "unique string describing the soundings origin (PLATFORM_SND-DIRECTION_LAT_LON_TIME)"
        dimension: ${runtime.sounding_dim}
    level:
        attrs:
            long_name: "sounding height"
        dimension: ${runtime.level_dim}
variables:
    launch_time:
        attrs:
            standard_name: "time"
            long_name: "time at which the sounding started"
        encodings:
            units: "seconds since 2020-01-01"
            calendar: "proleptic_gregorian"
        coordinates:
            - sounding
        internal_varname : "launch_time"
    flight_time:
        attrs:
            long_name: "time at pressure level"
            axis: "T"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            units: "seconds since 2020-01-01"
            calendar: "proleptic_gregorian"
        coordinates:
            - sounding
            - level
        internal_varname : "flight_time"
    dz:
        attrs:
            long_name: "ascent/descent rate of measuring device"
            description: "ascent rate is positive/ decent rate is negative"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            units: "m/s"
        coordinates:
            - sounding
            - level
        internal_varname : "ascent_rate"
    p:
        attrs:
            standard_name: "air_pressure"
            long_name: "pressure"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            units: "Pa"
        coordinates:
            - sounding
            - level
        internal_varname : "pressure"
    alt:
        attrs:
            standard_name: "geopotential_height"
            long_name: "geopotential height retrieved from PTU"
            positive: "up"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            units: "m"
        coordinates:
            - sounding
            - level
        internal_varname : "height"
    ta:
        attrs:
            standard_name: "air_temperature"
            long_name: "dry bulb temperature"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            units: "K"
        coordinates:
            - sounding
            - level
        internal_varname : "temperature"
    rh:
        attrs:
            standard_name: "relative_humidity"
            long_name: "relative humidity"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            units: "1"
        coordinates:
            - sounding
            - level
        internal_varname : "humidity"
    dp:
        attrs:
            standard_name: "dew_point_temperature"
            long_name: "dew point temperature"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            units: "K"
        coordinates:
            - sounding
            - level
        internal_varname : "dew_point"
    mr:
        attrs:
            standard_name: "humidity_mixing_ratio"
            long_name: "water vapor mixing ratio"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            units: "kg/kg"
        coordinates:
            - sounding
            - level
        internal_varname : "mixing_ratio"
    wspd:
        attrs:
            standard_name: "wind_speed"
            long_name: "wind speed"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            units: "m/s"
        coordinates:
            - sounding
            - level
        internal_varname : "wind_speed"
    wdir:
        attrs:
            standard_name: "wind_from_direction"
            long_name: "wind direction"
            coordinates: "launch_time flight_time lon lat p"
        encodings:
            units: "degree"
        coordinates:
            - sounding
            - level
        internal_varname : "wind_direction"
    lat:
        attrs:
            standard_name: "latitude"
            long_name: "latitude"
            axis: "Y"
        encodings:
            units: "degrees_north"
        coordinates:
            - sounding
            - level
        internal_varname : "latitude"
    lon:
        attrs:
            standard_name: "latitude"
            long_name: "latitude"
            axis: "Y"
        encodings:
            units: "degrees_north"
        coordinates:
            - sounding
            - level
        internal_varname : "longitude"
    sounding_id:
        attrs:
            long_name: "sounding identifier"
        format: ${main.platform}__{direction}__{lat:3.2f}_{lon:4.2f}__%Y%m%d%H%M
        coordinates:
            - sounding
        internal_varname : "sounding_id"
